# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Bash style word selection
autoload -U select-word-style
select-word-style bash

# Set up url quote magic
# TODO: Currently makes pasting unbearably slow, so disabling for now.
# autoload -Uz url-quote-magic
# zle -N self-insert url-quote-magic
# autoload -Uz bracketed-paste-magic
# zle -N bracketed-paste bracketed-paste-magic

# Edit current command line via ^X^E hotkey
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

# personal bin things
export PATH="${HOME?}/bin:${PATH}"
# set secret environment variables
source ~/.secretsrc
# set Datadog environment
source ~/.ddrc
# set switching iterm profiles when sshing
source ~/.colorssh.zsh

export EDITOR=vim # set vim as default editor

# *************
# P L U G I N S
# *************

# https://github.com/zsh-users/zsh-autosuggestions
# $ brew install zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# NOTE: Must be loaded before zsh-history-substring-search
# https://github.com/zsh-users/zsh-syntax-highlighting
# $ brew install zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# https://github.com/zsh-users/zsh-history-substring-search
# $ brew install zsh-history-substring-search
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# git clone https://github.com/larkery/zsh-histdb $HOME/.zsh/plugins/zsh-histdb
source $HOME/.zsh/plugins/zsh-histdb/sqlite-history.zsh
autoload -Uz add-zsh-hook
add-zsh-hook precmd histdb-update-outcome
_zsh_autosuggest_strategy_histdb_top() {
    local query="select commands.argv from
history left join commands on history.command_id = commands.rowid
left join places on history.place_id = places.rowid
where commands.argv LIKE '$(sql_escape $1)%'
group by commands.argv
order by places.dir != '$(sql_escape $PWD)', count(*) desc limit 1"
    suggestion=$(_histdb_query "$query")
}
ZSH_AUTOSUGGEST_STRATEGY=histdb_top
source $HOME/.zsh/plugins/zsh-histdb/histdb-interactive.zsh
bindkey '^r' _histdb-isearch
