# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt append_history
setopt share_history
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Bash style word selection
autoload -U select-word-style
select-word-style bash

# Set up url quote magic
# TODO: Currently makes pasting unbearably slow, so disabling for now.
# autoload -Uz url-quote-magic
# zle -N self-insert url-quote-magic
# autoload -Uz bracketed-paste-magic
# zle -N bracketed-paste bracketed-paste-magic

# Edit current command line via ^X^E hotkey
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# Set ESC key to enter vi mode
bindkey "\e" vi-cmd-mode

# Set Spaceship ZSH as a prompt
# autoload -U promptinit; promptinit
# prompt spaceship
source "$HOME/.zsh/spaceship/spaceship.zsh"

# iterm shell integration
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES

# set secret environment variables
source ~/.secretsrc
# set Datadog environment
source ~/.ddrc
source ~/.iterm.zsh
# set pythonrc
export PYTHONSTARTUP=~/.pythonrc

export EDITOR=vim # set vim as default editor

# personal bin things
export PATH="${HOME?}/bin:${PATH}"

# *************
# P L U G I N S
# *************

# https://github.com/zsh-users/zsh-autosuggestions
# $ brew install zsh-autosuggestions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# NOTE: Must be loaded before zsh-history-substring-search
# https://github.com/zsh-users/zsh-syntax-highlighting
# $ brew install zsh-syntax-highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://github.com/zsh-users/zsh-history-substring-search
# $ brew install zsh-history-substring-search
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=true
HISTORY_SUBSTRING_SEARCH_FUZZY=true

# **********
# pyenv
# **********

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

