# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Bash style word selection
autoload -U select-word-style
select-word-style bash

# Set up url quote magic
# TODO: Currently makes pasting unbearably slow, so disabling for now.
# autoload -Uz url-quote-magic
# zle -N self-insert url-quote-magic
# autoload -Uz bracketed-paste-magic
# zle -N bracketed-paste bracketed-paste-magic

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

# personal bin things
export PATH="${HOME?}/bin:${PATH}"
# set secret environment variables
source ~/.secretsrc
# set Datadog environment
source ~/.ddrc

export EDITOR=vim # set vim as default editor

# *************
# P L U G I N S
# *************

# https://github.com/zsh-users/zsh-autosuggestions
# $ brew install zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# NOTE: Must be loaded before zsh-history-substring-search
# https://github.com/zsh-users/zsh-syntax-highlighting
# $ brew install zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# https://github.com/zsh-users/zsh-history-substring-search
# $ brew install zsh-history-substring-search
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

